site_name: Webserver Templates

# Theme Settings
theme:
 name: material
 # Fonts
 font:
   text: Lexend Deca
 
 
 # Toggle / Dark <> Light mode
 palette: 
  - primary: black
    scheme: slate
    toggle:
      icon: material/toggle-switch-off-outline 
      name: Switch to dark mode
  - primary: brown
    scheme: default 
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode

# Plugins 
plugins:
  - tags
      tags_file: category.md

markdown_extensions:
  - attr_list
