site_name: Webserver Templates

# Theme Settings
theme:
 features:
   - content.code.annotate
   - content.tabs.link
 name: material
 # Fonts
 font:
   text: Lexend Deca
 
 
 # Toggle / Dark <> Light mode
 palette: 
  - primary: black
    accent: blue
    scheme: slate
    toggle:
      icon: material/toggle-switch-off-outline 
      name: Switch to dark mode
  - primary: teal
    accent: teal
    scheme: default 
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode

# Plugins 
plugins:
  - tags:
      tags_file: category.md

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - md_in_html
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true 
