site_name: Webserver Templates

# Theme Settings
theme:
 name: material
 font:
   text: Lexend Deca
 palette: 
  - primary: black
    scheme: slate
    toggle:
      icon: material/toggle-switch-off-outline 
      name: Switch to dark mode
  - primary: brown
    scheme: default 
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
