site_name: Webserver Templates

# Theme Settings
theme:
 name: material
 palette: 
  - primary: orange
    scheme: slate
    toggle:
      icon: material/toggle-switch-off-outline 
      name: Switch to dark mode
  - primary: deep orange
    scheme: default 
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
